version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-desenv
    volumes:
    - /Users/igor/volumes-docker/rabbitmq/:/var/lib/rabbitmq/mnesia
    ports:
      - 5672:5672
      - 15672:15672