mysql:
  image: mysql
  volumes:
    - /Users/igor/desenvolvimento/workspace/docker/mysql/database/:/var/lib/mysql/
  environment:
    - MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASSWORD=root
  ports: 
    - 3306:3306