version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-desev
    volumes:
      - c:/rabbitmqdata:/var/lib/rabbitmq/mnesia
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    image: mongo
    container_name: mongodb-desev
    volumes:
      - c:/mongodata:/data/db
    environment:
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=test
    ports:
      - 27017:27017
    depends_on:
      - rabbitmq
