version: '3'
services:
  mongodb:
    image: mongo:3.2
    container_name: mongodb-desenv
    volumes:
      - /Users/igor/volumes-docker/mongo/:/data/db
    environment:
    - MONGODB_ROOT_PASSWORD=password123
    ports:
    - 27017:27017