version: '3'
services:
  mongodb:
    image: mongo
     container_name: mongodb-desenv
    volumes:
      - /Users/igor/volumes-docker/mongo/:/data/db
    environment:
      - MONGODB_USERNAME=test1
      - MONGODB_PASSWORD=test1      
  ports: 
    - 27017:27017
